import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
      },
      bg:{
        width: '100%',
        height: '100%',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      main:{
        position: 'relative',
        bottom: 32,
        backgroundColor: 'white',
        width: '90%',
        height: '80%',
        alignItems: 'center',
        borderWidth: 5,
        borderRadius: 15,
        borderColor: 'lightblue',
      },
      viewtitle:{
        backgroundColor: 'lightgray',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomWidth: 3,
        borderColor: 'lightblue',
        width: '100%',
        height: '10%',
        alignItems: 'center',
        justifyContent: 'center',
      },
      viewdate:{
        margin: 10,
        backgroundColor: 'lightgray',
        top: 10,
        width: '30%',
        height: '5%',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: 'lightblue',
      },
      viewselecione:{
        borderTopWidth: 3,
        borderColor: 'lightblue',
        top: 20,
        width: '100%',
        height: '10%',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 20
      },
      votacaoselec:{
          backgroundColor: 'lightgray',
          top: 20,
          width: '55%',
          height: '40%',
          borderRadius: 10,
          borderWidth: 3,
          borderColor: 'lightblue',
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          padding: 3,
          gap: 2,
      },
      votacao:{
          backgroundColor: 'lightgray',
          top: 40,
          width: '95%',
          height: '50%',
          borderRadius: 10,
          borderWidth: 3,
          borderColor: 'lightblue',
          flexDirection: 'row',
          alignItems: 'center',
          padding: 3,
          gap: 2,
      },
      gridvotacao:{
          borderWidth: 2,
          borderRadius: 5,
          borderColor: 'gray',
          width: '33%',
          height: '70%',
          backgroundColor: 'white',
          justifyContent: 'center',
          alignItems: 'center',
      },
      gridvotacaoselec:{
          borderWidth: 2,
          borderRadius: 5,
          borderColor: 'gray',
          width: '90%',
          height: '90%',
          backgroundColor: 'white',
          justifyContent: 'center',
          alignItems: 'center',
      },
      smileicon:{
        width: 100,
        height: 100,
      },
      smileiconselec:{
        width: 130,
        height: 130,
      },
      textvotacao:{
        fontSize: 18,
        fontStyle: 'italic',
        textAlign: 'center',
      },
      viewinput:{
        width: '80%',
        height: '20%',
        top: 35,
        right: 25,
        alignItems: 'center',
        flexDirection: 'row',
      },
      viewobrigado:{
        width: '60%',
        height: '8%',
        top: 40,
        alignItems: 'center',
        flexDirection: 'row',
      },
      input:{
        backgroundColor: 'white',
        height: '80%',
        width: '73%',
        margin: 12,
        borderWidth: 1,
        borderColor: 'gray',
        padding: 10,
      },
      numerodevotation1:{
        margin: 6,
        borderBottomLeftRadius: 3,
        borderBottomRightRadius: 3,
        backgroundColor: 'lightgreen',
        width: '100%',
        top: 5,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
      },
      numerodevotation2:{
        margin: 6,
        borderBottomLeftRadius: 3,
        borderBottomRightRadius: 3,
        backgroundColor: 'yellow',
        width: '100%',
        top: 5,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
      },
      numerodevotation3:{
        margin: 6,
        borderBottomLeftRadius: 3,
        borderBottomRightRadius: 3,
        backgroundColor: '#ff6961',
        width: '100%',
        top: 5,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
      },
      textnumerodevotation:{
        fontSize: 20,
      },
      botaoimprov:{
        backgroundColor: 'lightgray',
        borderWidth: 2,
        borderColor: 'gray',
        borderRadius: 30,
        width: '35%',
        height: '40%',
        alignItems: 'center',
        justifyContent: 'center',
      },
      imgskcpo:{
        width: 60,
        height: 60,
        position: 'absolute',
        left: 120,
      },
      botaoobg:{
        backgroundColor: 'lightgray',
        borderWidth: 2,
        borderColor: 'gray',
        borderRadius: 30,
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
      },
      inputHome:{
        borderWidth: 1,
        height: 35,
        width: 200,
        padding: 10,
        top: 10,
      },
      toucavel:{
        width: '100%',
      },
      menu:{
        position: 'absolute',
        borderWidth: 3,
        borderColor: 'lightblue',
        width: '102%',
        height: 70,
        bottom: -2,
        display: 'flex',
        flexDirection: 'row',
        backgroundColor: 'white',
        justifyContent: 'center',
        gap: 80,
    },
    iconmenu:{
        width: 30,
        height: 30,
        top: 15
    },
});